#!/bin/bash

while true
do
    i=0
    #generate random number between 1-7
    #x=$(((RANDOM%7)+1))

    #generate random number between 0-3
    randdirec=$((RANDOM%4))

            case $randdirec in
                0)
                    #press 1
                    xdotool key 1
                ;;

                1)
                    #press 2
                    xdotool key 2
                ;;

		2)
		     #press 3
                     xdotool key 3  
		;;

	 	3)
		      #press 1
		      xdotool key 1

                ;;

                *)
                ;;
            esac
            randdirec=0
            #wait 0.01 seconds until the next iteration 
            sleep 0.50
            #i=$((i+1))
    done

done
